version: "3.8"

services:
  hasheo:
    build: .
    container_name: hasheo
    volumes:
      - .:/app            
    working_dir: /app     
    command: python main.py
    # debug(interaccion)
    tty: true             